---

- name: Remove temporary directory for this test
  file:
    dest: "{{ GISLAB_PATH_TMP }}"
    state: absent
  ignore_errors: yes
  changed_when: False

- name: Testing of GIS.lab is done
  shell: date -R
  ignore_errors: yes
  changed_when: False

# vim: set ts=8 sts=2 sw=2 et:
