---
#
### SERVER STATISTICS - MUNIN ###
#
# Install statistics monitoring system.


- name: Install packages
  apt:
    name:
    - munin
    - munin-node
    - munin-plugins-extra
    force: yes
    install_recommends: no
    state: latest


### MUNIN
- name: Configure Munin master
  template:
    src: munin/munin.conf.j2
    dest: /etc/munin/munin.conf
  notify:
    - service munin-node restart

- name: Configure Munin node
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {
        src: "munin/munin-node.conf.j2",
        dest: "/etc/munin/munin-node.conf"
      }
    - {
        src: "munin/munin-node.j2",
        dest: "/etc/munin/plugin-conf.d/munin-node"
      }
  notify:
    - service munin-node restart


### MUNIN PLUGINS
- name: Install custom Munin plugins
  copy:
    src: static/munin-plugins/
    dest: /usr/share/munin/plugins
  notify:
    - service munin-node restart

- name: Remove existing Munin plugins
  shell: rm -f /etc/munin/plugins/*

- name: Enable only required Munin plugins
  file:
    src: "/usr/share/munin/plugins/{{ item }}"
    dest: "/etc/munin/plugins/{{ item }}"
    state: link
  with_items:
    - cpu
    - cpu_by_process
    - df
    - diskstats
    - iostat
    - iostat_ios
    - load
    - memory
    - multips_memory
    - processes
    - swap
    - uptime
    - vmstat
  notify:
    - service munin-node restart


- name: Remove unnecessary Munin configuration
  file:
    path: /etc/cron.d/munin-node
    state: absent
  notify:
    - service munin-node restart


- name: Publish statistics
  file:
    src: /var/cache/munin/www
    dest: "{{ GISLAB_PATH_WWW }}/stats"
    state: link
    force: yes


### CRON
- name: Create directory for Munin script
  file:
    path: "{{ GISLAB_PATH_SYSTEM }}/stats"
    state: directory

- name: Install Munin statistics update script
  template:
    src: munin/update-stats.sh.j2
    dest: "{{ GISLAB_PATH_SYSTEM }}/stats/update-stats.sh"
    mode: 0755

- name: Activate Munin cron job
  template:
    src: cron/munin.j2
    dest: /etc/cron.d/munin


### EMAIL
- name: Add service user mail alias
  lineinfile:
    dest: /etc/aliases
    line: "munin: root"
    state: present

- name: Activate new mail alias
  command: newaliases


- meta: flush_handlers

# vim: set ts=8 sts=2 sw=2 et:
