---
#
### Docker integration
#

- name: Install docker packages
  apt:
    name:
      - docker.io
      - python3-docker

- name: Install docker packages (pip)
  pip:
    name:
      - compose
      - docker-compose==1.23

- name: Add provisioning user to the docker group
  user:
    name: "{{ GISLAB_PROVISIONING_USER }}"
    groups: docker
    append: yes


- name: Create docker directory
  file:
    path: "{{ docker_dir }}"
    state: directory
    mode: 0755

# vim: set ts=8 sts=2 sw=2 et:
