---
#
### Docker integration
#

- name: Install docker packages
  apt:
    name: "{{ item }}"
  with_items:
    - docker.io
    - docker-compose


- name: Add provisioning user to the docker group
  user:
    name: "{{ GISLAB_PROVISIONING_USER }}"
    groups: docker
    append: yes


- name: Create docker directory
  file:
    path: "{{ docker_dir }}"
    state: directory
    mode: 0755


- name: Install GIS.lab administrator tool
  copy:
    src: admin/
    dest: "{{ GISLAB_PATH_ADMIN }}/"
    mode: 0775

# vim: set ts=8 sts=2 sw=2 et:
