---
#
### Build GIS.lab Desktop client image for AWS
#

### GRUB
- name: Create directory for GRUB configuration
  file:
    path: "{{ root_dir }}/root/boot/grub"
    state: directory

- name: Install GRUB configuration file
  template:
    src: grub/menu.lst.j2
    dest: "{{ root_dir }}/root/boot/grub/menu.lst"


### IMAGE
- name: Build GIS.lab client image
  shell: gislab-client-image > /dev/null
  args:
    executable: /bin/bash

# vim: set ts=8 sts=2 sw=2 et:
