---

- name: Test IRC server connection
  shell: >
    echo -e "
    NICK test_{{ GISLAB_TEST_UNIQUE_STRING }}
    \nUSER test_{{ GISLAB_TEST_UNIQUE_STRING }} 8 * : test_{{ GISLAB_TEST_UNIQUE_STRING }}
    \nQUIT
    "
    | nc localhost 6667
    | grep "Welcome to GIS.lab IRC server"
  args:
    executable: /bin/bash
  ignore_errors: yes
  changed_when: False

# vim: set ts=8 sts=2 sw=2 et:
