---

- name: Test if PostgreSQL database is running and 'gislab' database contains PostGIS
  shell: >
    psql -U postgres -d gislab -tAc "SELECT postgis_version()"
  ignore_errors: yes
  changed_when: False

- name: Test if PostgreSQL database is tuned
  shell: >
    psql -U postgres -tAc "SELECT count(*) > 0 FROM pg_settings WHERE sourcefile like '%99-postgresql-tune.conf'"
    | grep 't'
  ignore_errors: yes
  changed_when: False

# vim: set ts=8 sts=2 sw=2 et:
