---
#
### NTP SERVER ###
#
# Install and configure time server for all network members.


- name: Install packages
  apt:
    name: ntp
    force: yes
    install_recommends: no
    state: latest


- name: NTP server configuration
  template:
    src: ntp/ntp.conf.j2
    dest: /etc/ntp.conf
  notify:
    - service ntp restart


- meta: flush_handlers

# vim: set ts=8 sts=2 sw=2 et:
