---
#
### MAIL SERVER - POSTFIX ###
#
# Install and configure email server.
#
# Logging: syslog


- name: Install packages
  apt:
    name:
      - bsd-mailx
      - mutt
      - postfix
      - postfix-ldap
      - sasl2-bin
    force: yes
    install_recommends: no
    state: latest


### POSTFIX
- name: Install main Postfix configuration file
  template:
    src: postfix/main.cf.j2
    dest: /etc/postfix/main.cf
  notify:
    - service postfix restart

- name: Install local LDAP aliases search table
  template:
    src: postfix/ldap-aliases.cf.j2
    dest: /etc/postfix/ldap-aliases.cf
  notify:
    - service postfix restart


### RELAY SERVER
- name: Remove existing SMTP relay server credentials
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/postfix/sasl_passwd
    - /etc/postfix/sasl_passwd.db

- name: Set SMTP relay server credentials if available
  template:
    src: postfix/sasl_passwd.j2
    dest: /etc/postfix/sasl_passwd
  when: GISLAB_SERVER_EMAIL_RELAY_LOGIN|default(None) != None
        and GISLAB_SERVER_EMAIL_RELAY_PASSWORD|default(None) != None
        and GISLAB_SERVER_EMAIL_RELAY_SERVER|default(None) != None

- name: Activate SMTP relay server credentials if available
  command: "{{ item }}"
  with_items:
    - chmod 0600 /etc/postfix/sasl_passwd
    - postmap /etc/postfix/sasl_passwd
  when: GISLAB_SERVER_EMAIL_RELAY_LOGIN|default(None) != None
        and GISLAB_SERVER_EMAIL_RELAY_PASSWORD|default(None) != None
        and GISLAB_SERVER_EMAIL_RELAY_SERVER|default(None) != None


### EMAIL ALIASES
- name: Add service user mail alias
  lineinfile:
    dest: /etc/aliases
    line: "postmaster: root"
    state: present

- name: Activate new mail alias
  command: newaliases


- name: Setup correct hostname for outgoing emails generated localy
  shell: echo "server.gis.lab" > /etc/mailname

- meta: flush_handlers

# vim: set ts=8 sts=2 sw=2 et:
