---
#
### DNS SERVER - BIND ###
#
# Install and configure GIS.lab's internal DNS records 'gis.lab'.
#
# Logging: syslog


- name: Install packages
  apt:
    name:
      - bind9
      - resolvconf
    force: yes
    install_recommends: no
    state: latest


- name: Install DNS server configuration
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {
        src: "bind/bind9.j2",
        dest: "/etc/default/bind9"
      }
    - {
        src: "bind/named.conf.j2",
        dest: "/etc/bind/named.conf"
      }
    - {
        src: "bind/named.conf.options.j2",
        dest: "/etc/bind/named.conf.options"
      }
    - {
        src: "bind/named.conf.local.j2",
        dest: "/etc/bind/named.conf.local"
      }
    - {
        src: "bind/db.gis.lab.j2",
        dest: "/etc/bind/db.gis.lab"
      }
    - {
        src: "bind/db.192.j2",
        dest: "/etc/bind/db.192"
      }
  notify:
    - service named stop

- name: Install resolvconf configuration
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {
        src: "resolvconf/tail.j2",
        dest: "/etc/resolvconf/resolv.conf.d/tail"
      }


- meta: flush_handlers

# vim: set ts=8 sts=2 sw=2 et:
