---
#
### LOGCHECK ###
#
# Install and configure services logs checking.


- name: Install packages
  apt:
    name:
      - logcheck
      - logcheck-database
    force: yes
    install_recommends: no


- name: Configure logcheck
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {
        src: 'logcheck/logcheck.conf.j2',
        dest: '/etc/logcheck/logcheck.conf'
      }
    - {
        src: 'logcheck/logcheck.logfiles.j2',
        dest: '/etc/logcheck/logcheck.logfiles'
      }

- name: Activate logcheck
  template:
    src: cron/logcheck.j2
    dest: /etc/cron.d/logcheck

# vim: set ts=8 sts=2 sw=2 et:
