---

- name: Test client image file
  shell: >
    file {{ root_dir }}/image/gislab.img
    | grep "Squashfs filesystem, little endian"
  ignore_errors: yes
  changed_when: False

- name: Test if VirtualBox guest additions are installed
  shell: >
    find {{ root_dir }}/root/lib/modules
    | grep "vboxguest.ko"
  when: GISLAB_CLIENT_VIRTUALBOX_SUPPORT
  ignore_errors: yes
  changed_when: False

# vim: set ts=8 sts=2 sw=2 et:
