---
#
###  DEFAULT WEB PAGE ###
#
# Install web server and configure default web page content.
#
# Logging: syslog


- name: Install packages
  apt:
    name: nginx
    force: yes
    install_recommends: no
    state: latest


### NGINX
- name: Configure Nginx
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - {
        src: "nginx/nginx.conf.j2",
        dest: "/etc/nginx/nginx.conf"
      }
    - {
        src: "nginx/proxy-parameters.j2",
        dest: "/etc/nginx/proxy-parameters"
      }
  notify:
    - service nginx restart

- name: Configure default Nginx virtualhost
  template:
    src: nginx/site-default.j2
    dest: /etc/nginx/sites-available/default
  notify:
    - service nginx restart


### WEB CONTENT
- name: Install default web page content
  template:
    src: index.html
    dest: "{{ GISLAB_PATH_WWW }}/index.html"

- name: Add 'gislab_version' file to default web content
  file:
    src: /etc/gislab_version
    dest: "{{ GISLAB_PATH_WWW }}/gislab_version"
    state: link


### EMAIL
- name: Add service user mail alias
  lineinfile:
    dest: /etc/aliases
    line: "www-data: root"
    state: present

- name: Activate new mail alias
  command: newaliases


- meta: flush_handlers

# vim: set ts=8 sts=2 sw=2 et:
