---
#
### CONNECTION FORWARDING ###
#
# Activate connection forwarding for all GIS.lab network members


- name: Activate connection forwarding
  template:
    src: systemd/gislab-connection-forwarding.service.j2
    dest: /etc/systemd/system/gislab-connection-forwarding.service
  notify:
    - service gislab-connection-forwarding disable

- meta: flush_handlers

# vim: set ts=8 sts=2 sw=2 et:
