---

- name: Test if LDAP tree contains GIS.lab organization
  shell: >
    ldapsearch -Q -LLL -Y EXTERNAL -H ldapi:/// '(o=gis.lab)'
    | grep "dn: dc=gis,dc=lab"
  ignore_errors: yes
  changed_when: False

# vim: set ts=8 sts=2 sw=2 et:
